### PR TITLE
Bad resource file upload test. Closes #130.

### LINKED ISSUE #130: Show error message when trying to upload and parse malformed CSV
I tried to upload resource datafile which actually was html file with ```.csv``` extension. Didn't see any error message except one in dev console:

Looks like parsing errors are thrown silently for regular user and this may lead to bad UX.

## Task
If user is trying to upload malformed ```.csv``` show modal box with thrown error and tell user that it possible means bad/wrong file content.

### PR DESCRIPTION
**Pull request by alexeyk**
Bad resource file upload notification test 
Closes #130

### CODE REVIEW

**Comment by pwalsh** [comment]
@alexeyk @gvidon tests fail. See travis output.

**Comment by gvidon** [comment]
I saw, will get to this by Monday.

-----Исходное сообщение-----
От: "Paul Walsh" <notifications@github.com>
Отправлено: ‎29.‎08.‎2015 11:50
Кому: "okfn/datapackagist" <datapackagist@noreply.github.com>
Копия: "Gvidon Malyarov" <gvidon@ottofeller.com>
Тема: Re: [datapackagist] Bad resource file upload test (#130) (#137)

@alexeyk @gvidon tests fail. See travis output.

**Comment by gvidon** [comment]
Tests passed after reloading them manually on travis.

**Comment by gvidon** [comment]
Ready

**Pull request merged**
