### PR TITLE
Use CORS proxy. Closes #148.

### LINKED ISSUE #148: Clarification (API endpoint security)
In Chrome this integration example with a CKAN endpoint:
http://datapackagist.okfnlabs.org/base/from/?url=http%3A%2F%2Fdatahub.io%2Fapi%2Faction%2Fpackage_show%3Fid%3Dpopulation-number-by-governorate-age-group-and-gender-2010-2014
works as expected whereas this example using a DKAN endpoint:
http://datapackagist.okfnlabs.org/base/from/?url=http%3A%2F%2Fopendata.cambridgeshireinsight.org.uk%2Fapi%2F3%2Faction%2Fpackage_show%3Fid%3D965509fe-fedc-474c-aa00-3c647721de31
does nothing.
Chrome console gives:
Error while process. End point request failed: Error: Origin is not allowed by Access-Control-Allow-Origin
image
Looking at the response headers the datahub.io endpoint includes the following headers that are not returned from the opendata.cambridgeshireinsight.org.uk endpoint:
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, PUT, GET, DELETE, OPTIONS
Access-Control-Allow-Headers: X-CKAN-API-KEY, Authorization, Content-Type
image

It would be worth confirming the required response headers for any endpoint to work with the tool.

From a user experience perspective at first glance it looks like the packagist tool doesn't work.  Is there an easy way to catch this issue and display it in a user friendly manner, perhaps with a link to help portal owners resolve potential endpoint issues with their respective technology providers?

### PR DESCRIPTION
**Pull request by gvidon**
To avoid ```access-control-allow-origin``` header restrictions when requesting remote resources, use proxy like this http://crossorigin.me/http://some.resource/url.csv

### CODE REVIEW

**Comment by pwalsh** [comment]
As I noted in #148 just now, I don't think I want to introduce hacks around servers that do not allow cross origin requests. 

The problem is that the server does not let us work with its data, and this is not, IMHO, an issue that DataPackagist should solve. 

Perhaps an error that says "hey, that server will not let us use its data" would be more appropriate.

@gvidon what do you think?

**Comment by gvidon** [comment]
@pwalsh you are right about hacks, I agree. But this way we will sacrifice UX. Because no one want to know anything about http headers and those guys who intentionally or unintentionally sets them up, users want to upload file — fast and with no issues. So, you need to decide what is important.

**Comment by richhall** [comment]
Hi,

It looks like http://datapackagist.herokuapp.com/cors-proxy isn't adding the access-control-allow-origin header?: Example:

http://datapackagist.herokuapp.com/cors-proxy/https://rawgit.com/richhall/4f2b94ae058317f6ac39/raw/7fbbd5965410898e0562103c1481e72a1b52765f/opendata_cambridgeshireinsight_org_uk_example.json

**Comment by gvidon** [comment]
@richhall I'm not really sure if it should add ```access-control-allow-origin: *``` header to the response. There is no need in it as client CSV and client app files are loaded from the same domain.

**Comment by pwalsh** [comment]
Definitely: it is a proxy for use by this app only.

**Comment by richhall** [comment]
good point! - I think what I meant to ask was does the config needs to specify http://datapackagist.okfnlabs.org/corsproxy instead of http://datapackagist.herokuapp.com/cors-proxy -otherwise it appears as a cross origin request?

**Comment by pwalsh** [comment]
@richhall ah, I see :).

**Comment by gvidon** [comment]
@richhall yes, in current implementation you need to manually define app host name in config.

**Pull request merged**
