### PR TITLE
Bundles separation and unused dependencies

### PR DESCRIPTION
**Pull request by gvidon**
* Build ```vendor.min.js``` on base of ```package.json.dependencies``` list, exclude these packages from ```app.min.js```
* created a gulp task that throw list of unused dependencies  into stderr — ```gulp check-deps```
* cleaned up unused dependencies.

### CODE REVIEW

**Comment by pwalsh** [comment]
@gvidon 

1. See the Travis build fail - is there an issue there, or a false alarm?
2. Are you sure this packages only what we need into vendor.min?

**Comment by gvidon** [comment]
Didn't see Travis issue when did the pr, will take a look later.

If you are talking about dev packages in .dependencies - I planned to fix that in #124.

**Comment by gvidon** [comment]
@pwalsh looks like from-remote test failed because of a wrong header, error log points there https://github.com/assaf/zombie/blob/master/src/xhr.js#L173 I did tests locally several times, with no issues.

**Comment by gvidon** [comment]
@pwalsh 
* merged master in to sync list of dependencies and fix conflicts
* installed all node modules from scratch after it, and all tests passed.

I believe it is ready to be merged.

**Comment by pwalsh** [comment]
done.

**Pull request merged**
